trigger:
 - main

stages:
- stage: Job_Worker_Build
  displayName: Job_Worker_Build
  jobs:
  - job: 'Build_v1'
    displayName: Building amit-spring-app docker image for eus2 with v1 tag
    pool:  
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-amitacr-srvc-con'
        repository: 'myrepo/amit-spring-app'
        command: 'buildAndPush'
        Dockerfile: 'eus2/Dockerfile'
        tags: 'v1'
      
- stage: Job_Worker_Build_v2
  displayName: Job_Worker_Buildv2
  jobs:
  - job: 'Build_v2'
    displayName: Building for myMarket-USloader with v2 tag
    pool:  
      vmImage: ubuntu-latest
    steps:   
    - checkout:  git://amit-apps/myMarket-USloader@eus2
    - task: MavenAuthenticate@0
      displayName: Maven Authenticate
      inputs:
        artifactsFeeds: 'amit-apps'
        mavenServiceConnections: 'singh-ptw-amit-apps'
    - task: Maven@3
      displayName: Maven pom.xml
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
          ls target/*

    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-amitacr-srvc-con'
        repository: 'myrepo/amit-spring-app'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'v2'
      
- stage: Job_Worker_Build_v3
  displayName: Job_Worker_Buildv3
  jobs:
  - job: 'Build_v3'
    displayName: Building for myMarket-MACloader with v3 tag
    pool:  
      vmImage: ubuntu-latest
    steps:   
    - checkout:  git://amit-apps/myMarket-MACloader@eus2
    - task: MavenAuthenticate@0
      displayName: Maven Authenticate
      inputs:
        artifactsFeeds: 'amit-apps'
        mavenServiceConnections: 'singh-ptw-amit-apps'
    - task: Maven@3
      displayName: Maven pom.xml
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
          ls target/*
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-amitacr-srvc-con'
        repository: 'myrepo/amit-spring-app'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'v3'
