steps:
  - script : |
      echo 'Param containerRegistry :- ${{ parameters.containerRegistry }}'
      echo 'Param dockerFile :- ${{ parameters.dockerFile }}'
      echo 'Param repository :- ${{ parameters.repo }}'
      echo 'Param tags :- ${{ parameters.tag }}'
      echo 'Variable buildContext :- $(Pipeline.Workspace)/javaArchive'
      echo 'artifactId :- $(Pipeline.Workspace)/javaArchive'
  - checkout: self
    persistCredentials: true
  - download: current
    artifact: javaArchive

  - task: Docker@2
    displayName: 'Login to $(push_acr_repo_prod)'
    inputs:
      containerRegistry: $(push_acr_repo_prod)
      command: 'login'

  - task: Docker@2
    displayName: 'Login to $(push_acr_repo)'
    inputs:
      containerRegistry: $(push_acr_repo)
      command: 'login'

  - task: Docker@2
    displayName: 'Build and Push Image'
    inputs:
      command: 'buildAndPush'
      containerRegistry: ${{parameters.containerRegistry}}
      dockerFile: ${{parameters.dockerFile}}
      repository: ${{parameters.repo}}
      tags: ${{parameters.tag}}
      buildContext: $(Pipeline.Workspace)/javaArchive
