  steps:
    - script: 'ls -la'
    - task: HelmInstaller@0
      inputs:
        helmVersion: '3.4.0'
        installKubectl: true
    - ${{ if eq(parameters.environment, 'PROD') }}:
        - task: HelmDeploy@0
          displayName: Deploy configmaps to ${{parameters.environment}} namespace for values file ${{ parameters.valuesFile }}
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: $(prod_kubernetesCluster)
            command: upgrade
            chartType: FilePath
            useClusterAdmin: true
            chartPath: 'rt-sift-chart'
            releaseName: helm-sift-configmap
            resetValues: true
            force: true
            arguments: '--values=${{ parameters.valuesFile }}'
            namespace: ${{ parameters.namespace }}
    - ${{ if eq(parameters.environment, 'UAT') }}:
        - task: HelmDeploy@0
          displayName: Deploy configmaps to ${{parameters.environment}} namespace for values file ${{ parameters.valuesFile }}
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: $(test_kubernetesServiceEndpoint)
            command: upgrade
            useClusterAdmin: true
            chartType: FilePath
            chartPath: 'rt-sift-chart'
            releaseName: helm-sift-configmap
            resetValues: true
            force: true
            arguments: '--values=${{ parameters.valuesFile }}'
            namespace: ${{ parameters.namespace }}
